# Generated by Django 5.1.7 on 2026-03-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_gal', models.CharField(help_text='Identificador único do sistema GAL — anonimizado.', max_length=50, unique=True, verbose_name='Número GAL')),
                ('codigo_interno', models.CharField(help_text='Formato N/AA (ex: 1/26 = 1ª amostra do ano 2026).', max_length=20, unique=True, verbose_name='Código interno')),
                ('data_coleta', models.DateField(blank=True, help_text='Preenchida a partir do CSV do GAL.', null=True, verbose_name='Data de coleta')),
                ('data_recebimento', models.DateField(verbose_name='Data de recebimento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('I', 'Indeterminado')], max_length=1, null=True, verbose_name='Sexo')),
                ('idade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Município')),
                ('cid', models.CharField(blank=True, max_length=20, verbose_name='CID')),
                ('status', models.CharField(choices=[('recebida', 'Recebida'), ('aliquotada', 'Aliquotada'), ('em_processamento', 'Em processamento'), ('amplificada', 'Amplificada'), ('resultado_liberado', 'Resultado liberado'), ('cancelada', 'Cancelada'), ('repeticao_solicitada', 'Repetição Solicitada')], db_index=True, default='recebida', max_length=30, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Amostra',
                'verbose_name_plural': 'Amostras',
                'ordering': ['-criado_em'],
            },
        ),
    ]
