# Generated by Django 5.1.7 on 2026-03-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_exame_gal', models.CharField(db_index=True, help_text='Identificador único do exame no GAL (coluna "Cód. Exame").', max_length=20, unique=True, verbose_name='Cód. Exame GAL')),
                ('numero_gal', models.CharField(db_index=True, help_text='Número da requisição do paciente no GAL.', max_length=30, verbose_name='Número GAL (Requisição)')),
                ('cod_amostra_gal', models.CharField(blank=True, help_text='Código da amostra física no GAL (coluna "Cód. Amostra").', max_length=20, verbose_name='Cód. Amostra GAL')),
                ('codigo_interno', models.CharField(blank=True, help_text='Formato N/AA atribuído pelo LACEN (ex: 1/26). Importado do GAL quando disponível; preenchido manualmente caso ausente.', max_length=20, null=True, unique=True, verbose_name='Código interno')),
                ('nome_paciente', models.CharField(max_length=200, verbose_name='Paciente')),
                ('nome_social', models.CharField(blank=True, max_length=200, verbose_name='Nome Social')),
                ('cns', models.CharField(blank=True, max_length=25, verbose_name='CNS')),
                ('cpf', models.CharField(blank=True, max_length=14, verbose_name='CPF')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Município de Residência')),
                ('uf', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('unidade_solicitante', models.CharField(blank=True, max_length=200, verbose_name='Unidade Solicitante')),
                ('municipio_solicitante', models.CharField(blank=True, max_length=100, verbose_name='Município Solicitante')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Material')),
                ('data_coleta', models.DateTimeField(blank=True, help_text='Coluna "Dt. Cadastro" do CSV GAL.', null=True, verbose_name='Data de Cadastro/Coleta (GAL)')),
                ('data_recebimento', models.DateTimeField(blank=True, help_text='Coluna "Dt. Recebimento" do CSV GAL.', null=True, verbose_name='Data de Recebimento')),
                ('status', models.CharField(choices=[('recebida', 'Recebida'), ('aliquotada', 'Aliquotada'), ('em_processamento', 'Em processamento'), ('amplificada', 'Amplificada'), ('resultado_liberado', 'Resultado liberado'), ('cancelada', 'Cancelada'), ('repeticao_solicitada', 'Repetição Solicitada')], db_index=True, default='recebida', max_length=30, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Amostra',
                'verbose_name_plural': 'Amostras',
                'ordering': ['-criado_em'],
            },
        ),
    ]
