# Generated by Django 5.1.7 on 2026-03-18 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amostras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='amostra',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amostras_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddIndex(
            model_name='amostra',
            index=models.Index(fields=['status'], name='amostras_am_status_5d8a1c_idx'),
        ),
        migrations.AddIndex(
            model_name='amostra',
            index=models.Index(fields=['numero_gal'], name='amostras_am_numero__20f9ea_idx'),
        ),
        migrations.AddIndex(
            model_name='amostra',
            index=models.Index(fields=['codigo_interno'], name='amostras_am_codigo__88de51_idx'),
        ),
    ]
