# Generated by Django 5.1.7 on 2026-03-20 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amostras', '0004_migrate_old_status_values'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='amostra',
            name='recebido_por',
            field=models.ForeignKey(blank=True, help_text='Operador que confirmou o recebimento/aliquotagem.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amostras_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Recebido por'),
        ),
    ]
