# Generated by Django 5.1.7 on 2026-03-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoAmostra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci_resultado', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo'), ('invalido', 'Inválido'), ('pendente', 'Pendente')], default='pendente', max_length=20, verbose_name='CI')),
                ('hpv16_resultado', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo'), ('invalido', 'Inválido'), ('pendente', 'Pendente')], default='pendente', max_length=20, verbose_name='HPV 16')),
                ('hpv18_resultado', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo'), ('invalido', 'Inválido'), ('pendente', 'Pendente')], default='pendente', max_length=20, verbose_name='HPV 18')),
                ('hpvar_resultado', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo'), ('invalido', 'Inválido'), ('pendente', 'Pendente')], default='pendente', max_length=20, verbose_name='HPV AR')),
                ('resultado_final', models.CharField(choices=[('hpv_detectado', 'HPV Detectado'), ('hpv_nao_detectado', 'HPV Não Detectado'), ('invalido', 'Inválido'), ('pendente', 'Pendente')], db_index=True, default='pendente', max_length=30, verbose_name='Resultado final')),
                ('confirmado_em', models.DateTimeField(blank=True, null=True, verbose_name='Confirmado em')),
                ('imutavel', models.BooleanField(default=False, help_text='True após confirmação definitiva. Resultado não pode ser alterado.', verbose_name='Imutável')),
            ],
            options={
                'verbose_name': 'Resultado da amostra',
                'verbose_name_plural': 'Resultados das amostras',
            },
        ),
        migrations.CreateModel(
            name='ResultadoPoco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('CI', 'Controle Interno (CI)'), ('HPV16', 'HPV 16'), ('HPV18', 'HPV 18'), ('HPV_AR', 'HPV Alto Risco (AR)')], max_length=10, verbose_name='Canal')),
                ('cq', models.FloatField(blank=True, help_text='Valor de Cq do PCR. Vazio = não amplificou (NaN no CSV).', null=True, verbose_name='Cq')),
                ('interpretacao', models.CharField(choices=[('positivo', 'Positivo'), ('negativo', 'Negativo'), ('invalido', 'Inválido'), ('pendente', 'Pendente')], default='pendente', max_length=20, verbose_name='Interpretação automática')),
                ('interpretacao_manual', models.CharField(blank=True, choices=[('positivo', 'Positivo'), ('negativo', 'Negativo'), ('invalido', 'Inválido'), ('pendente', 'Pendente')], max_length=20, null=True, verbose_name='Interpretação manual')),
                ('justificativa_manual', models.TextField(blank=True, help_text='Obrigatório quando interpretacao_manual é preenchido.', verbose_name='Justificativa da edição manual')),
            ],
            options={
                'verbose_name': 'Resultado por poço',
                'verbose_name_plural': 'Resultados por poço',
                'ordering': ['poco__posicao', 'canal'],
            },
        ),
    ]
