# Generated by Django 5.1.7 on 2026-03-18 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placas', '0002_initial'),
        ('resultados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoamostra',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por'),
        ),
        migrations.AddField(
            model_name='resultadoamostra',
            name='poco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_amostra', to='placas.poco', verbose_name='Poço'),
        ),
        migrations.AddField(
            model_name='resultadopoco',
            name='poco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='placas.poco', verbose_name='Poço'),
        ),
        migrations.AlterUniqueTogether(
            name='resultadopoco',
            unique_together={('poco', 'canal')},
        ),
    ]
