# Generated by Django 5.1.7 on 2026-03-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoamostra',
            name='resultado_final',
            field=models.CharField(choices=[('hpv_nao_detectado', 'HPV não detectável'), ('hpv16', 'HPV-16 detectável'), ('hpv18', 'HPV-18 detectável'), ('hpv_ar', 'HPV AR detectável'), ('hpv18_ar', 'HPV-18 e HPV AR detectáveis'), ('hpv16_ar', 'HPV-16 e HPV AR detectáveis'), ('hpv16_18', 'HPV-16 e HPV-18 detectáveis'), ('hpv16_18_ar', 'HPV-16, HPV-18 e HPV AR detectáveis'), ('invalido', 'Inválido'), ('inconclusivo', 'Inconclusivo'), ('pendente', 'Pendente')], db_index=True, default='pendente', max_length=30, verbose_name='Resultado final'),
        ),
    ]
