# Generated by Django 5.1.7 on 2026-04-06 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0003_expand_resultado_final_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultadoamostra',
            options={'ordering': ['-confirmado_em', 'id'], 'verbose_name': 'Resultado da amostra', 'verbose_name_plural': 'Resultados das amostras'},
        ),
    ]
