# Generated by Django 5.1.7 on 2026-04-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0004_alter_resultadoamostra_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoamostra',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
