# Generated by Django 5.1.7 on 2026-04-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultados', '0005_resultadoamostra_atualizado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoamostra',
            name='cn_valido',
            field=models.BooleanField(default=True, help_text='False se o poço CN falhou na validação mas o import foi forçado.', verbose_name='CN válido'),
        ),
        migrations.AddField(
            model_name='resultadoamostra',
            name='cp_valido',
            field=models.BooleanField(default=True, help_text='False se o poço CP falhou na validação mas o import foi forçado.', verbose_name='CP válido'),
        ),
        migrations.AddField(
            model_name='resultadoamostra',
            name='motivo_controle_invalido',
            field=models.TextField(blank=True, help_text='Detalhamento dos erros de CP e CN quando forçado.', verbose_name='Motivo da inválida'),
        ),
    ]
