# Generated by Django 5.1.7 on 2026-03-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='numero_cracha',
            field=models.CharField(blank=True, db_index=True, help_text='Código lido pelo leitor de crachá (barcode/RFID). Opcional.', max_length=50, null=True, unique=True, verbose_name='Número do crachá'),
        ),
    ]
