# Generated by Django 5.1.7 on 2026-03-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalWsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=100, verbose_name='Usuário GAL')),
                ('senha', models.CharField(blank=True, help_text='Armazenada em texto simples — use usuário dedicado de integração.', max_length=255, verbose_name='Senha GAL')),
                ('codigo_laboratorio', models.CharField(blank=True, help_text='Parâmetro "laboratorio" usado em buscarExames.', max_length=50, verbose_name='Código do laboratório')),
                ('url_ws', models.CharField(blank=True, default='https://gal.riograndedosul.sus.gov.br/webservice/automacao', max_length=255, verbose_name='URL do WebService')),
                ('verificar_ssl', models.BooleanField(default=False, help_text='Desative se o servidor GAL usar certificado auto-assinado.', verbose_name='Verificar SSL')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração GAL WS',
                'verbose_name_plural': 'Configuração GAL WS',
            },
        ),
    ]
