# Generated by Django 5.1.7 on 2026-03-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(blank=True, max_length=50, verbose_name='Protocolo')),
                ('status_placa', models.CharField(choices=[('aberta', 'Aberta'), ('submetida', 'Submetida ao termociclador'), ('resultados_importados', 'Resultados importados')], db_index=True, default='aberta', max_length=30, verbose_name='Status da placa')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Placa',
                'verbose_name_plural': 'Placas',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Poco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.CharField(help_text='Formato linha+coluna: A01 … H12', max_length=3, verbose_name='Posição')),
                ('tipo_conteudo', models.CharField(choices=[('amostra', 'Amostra'), ('cn', 'Controle Negativo'), ('cp', 'Controle Positivo'), ('vazio', 'Vazio')], default='amostra', max_length=20, verbose_name='Tipo de conteúdo')),
            ],
            options={
                'verbose_name': 'Poço',
                'verbose_name_plural': 'Poços',
                'ordering': ['posicao'],
            },
        ),
    ]
