# Generated by Django 5.1.7 on 2026-03-18 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amostras', '0002_initial'),
        ('placas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='placa',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placas', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='poco',
            name='amostra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pocos', to='amostras.amostra', verbose_name='Amostra'),
        ),
        migrations.AddField(
            model_name='poco',
            name='placa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pocos', to='placas.placa', verbose_name='Placa'),
        ),
        migrations.AlterUniqueTogether(
            name='poco',
            unique_together={('placa', 'posicao')},
        ),
    ]
