# Generated by Django 5.1.7 on 2026-03-25 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0005_tipo_placa_placa_origem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placa',
            name='placa_origem',
            field=models.ForeignKey(blank=True, help_text='Preenchido somente em placas PCR criadas a partir de uma extração.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placas_pcr_derivadas', to='placas.placa', verbose_name='Placa de extração de origem'),
        ),
    ]
