# Generated by Django 5.1.7 on 2026-03-27 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0006_alter_placa_placa_origem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='placa',
            name='extracao_confirmada_por',
            field=models.ForeignKey(blank=True, help_text='Operador que confirmou a extração (scan do crachá).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracoes_confirmadas', to=settings.AUTH_USER_MODEL, verbose_name='Extração confirmada por'),
        ),
    ]
