# Generated by Django 5.1.7 on 2026-04-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0007_placa_extracao_confirmada_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placa',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, help_text='Gerado automaticamente: HPVe{DDMMAA}-{N} para extração (ex: HPVe010426-1) ou HPVp{DDMMAA}-{N} para PCR (ex: HPVp010426-1).', max_length=20, unique=True, verbose_name='Código da Placa'),
        ),
    ]
