# Generated by Django 5.1.7 on 2026-04-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placas', '0008_alter_placa_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='poco',
            name='grupo',
            field=models.PositiveSmallIntegerField(default=1, help_text='Grupo de reagentes ao qual este poço pertence (1, 2, 3...).', verbose_name='Grupo de extração'),
        ),
    ]
