# Generated by Django 5.1.7 on 2026-04-08 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001_initial'),
        ('placas', '0009_poco_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='placa',
            name='kit_interpretacao',
            field=models.ForeignKey(blank=True, help_text='Kit usado para interpretação dos resultados desta placa.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuracoes.kitinterpretacao', verbose_name='Kit de interpretação'),
        ),
    ]
