# Generated by Django 5.1.7 on 2026-04-08 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('placas', '0009_poco_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitInterpretacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('cq_controle_max', models.FloatField(default=25.0, help_text='CP: todos os canais devem ter Cq <= este valor. CN: CI deve ter Cq <= este valor.', verbose_name='Cq maximo controles')),
                ('cq_amostra_ci_max', models.FloatField(default=33.0, help_text='Amostra CI: positivo se Cq <= este valor.', verbose_name='Cq maximo CI amostra')),
                ('cq_amostra_hpv_max', models.FloatField(default=40.0, help_text='Amostra HPV: positivo se Cq <= este valor.', verbose_name='Cq maximo HPV amostra')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Kit de interpretacao',
                'verbose_name_plural': 'Kits de interpretacao',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ReacaoProtocolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Protocolo de reacao',
                'verbose_name_plural': 'Protocolos de reacao',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PlacaGrupoReacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.PositiveSmallIntegerField(verbose_name='Grupo')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupo_reacoes', to='placas.placa', verbose_name='Placa')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configuracoes.reacaoprotocolo', verbose_name='Protocolo de reacao')),
            ],
            options={
                'verbose_name': 'Reacao por grupo da placa',
                'verbose_name_plural': 'Reacoes por grupo da placa',
                'unique_together': {('placa', 'grupo')},
            },
        ),
        migrations.CreateModel(
            name='ReacaoReagente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Reagente')),
                ('volume_por_reacao', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Volume por reacao (uL)')),
                ('ordem', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem')),
                ('protocolo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagentes', to='configuracoes.reacaoprotocolo', verbose_name='Protocolo')),
            ],
            options={
                'verbose_name': 'Reagente',
                'verbose_name_plural': 'Reagentes',
                'ordering': ['ordem', 'id'],
                'unique_together': {('protocolo', 'nome')},
            },
        ),
    ]
