# Generated by Django 5.1.7 on 2026-04-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_seed_ibmp'),
    ]

    operations = [
        migrations.AddField(
            model_name='reacaoprotocolo',
            name='margem_percentual',
            field=models.FloatField(default=10.0, help_text='Percentual adicional sobre o volume total (ex: 10 = +10%). Compensa perdas de pipetagem.', verbose_name='Margem extra (%)'),
        ),
    ]
